"""
Dump all data from release_catalog.db into data/data_dump.sql as INSERT statements.
The dump does NOT include CREATE TABLE statements — use init_db.py for schema.

Usage:
    uv run dump_data.py
    uv run dump_data.py --db-path /path/to/other.db
    uv run dump_data.py --dump-path /path/to/output.sql
"""

import argparse
import os
import sqlite3

from global_config import BASEPATH, DB_PATH

DUMP_PATH = os.path.join(BASEPATH, "data_dump.sql")


def dump_data(db_path: str = DB_PATH, dump_path: str = DUMP_PATH) -> None:
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    )
    tables = [row[0] for row in cursor.fetchall()]

    lines = [
        "-- Data dump from release_catalog.db",
        "-- Restore with: uv run restore_data.py",
        "-- Generated by dump_data.py",
        "",
        "PRAGMA foreign_keys = OFF;",
        "",
    ]

    for table in tables:
        cursor.execute(f"SELECT * FROM {table}")
        rows = cursor.fetchall()
        if not rows:
            continue

        col_names = [desc[0] for desc in cursor.description]
        cols = ", ".join(col_names)
        placeholders = ", ".join("?" * len(col_names))

        lines.append(f"-- {table} ({len(rows)} rows)")
        for row in rows:
            # Build a safe SQL INSERT using Python's parameter substitution rendered as literals
            values = ", ".join(_sql_literal(v) for v in row)
            lines.append(f"INSERT INTO {table} ({cols}) VALUES ({values});")
        lines.append("")

    lines.append("PRAGMA foreign_keys = ON;")

    with open(dump_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    conn.close()
    print(f"Dumped {len(tables)} tables to {dump_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Dump all table data from the release catalog database to a SQL file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--db-path",
        default=DB_PATH,
        metavar="PATH",
        help="Path to the SQLite database file (default: %(default)s)",
    )
    parser.add_argument(
        "--dump-path",
        default=DUMP_PATH,
        metavar="PATH",
        help="Path to write the SQL dump file (default: %(default)s)",
    )
    args = parser.parse_args()
    dump_data(os.path.abspath(args.db_path), os.path.abspath(args.dump_path))


def _sql_literal(value) -> str:
    """Render a Python value as a SQL literal."""
    if value is None:
        return "NULL"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    # Escape single quotes by doubling them
    return "'" + str(value).replace("'", "''") + "'"


if __name__ == "__main__":
    main()
